# Generated by Django 5.0.3 on 2025-07-17 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogCategory',
            new_name='Category',
        ),
    ]
